language: python
python:
    - "3.8"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - cp src/config.sample.cpp src/config.cpp
    - platformio run