version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
install:
- sh: >-
    source $HOME/venv3.8/bin/activate

    pip install platformio
build_script:
- sh: >-
    cp src/config.sample.cpp src/config.cpp

    platformio run
test: off
deploy: off