version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
install:
- sh: >-
    yes | sudo apt install python3-pip

    sudo python3 -m pip install platformio
build_script:
- sh: >-
    cp src/config.sample.h src/config.h

    platformio run
test: off
deploy: off